apiVersion: apps/v1
kind: Deployment
metadata:
  name: facts-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: facts-fe
  template:
    metadata:
      labels:
        app: facts-fe
    spec:
      containers:
      - name: facts-frontend
        image: shekeriev/k8s-facts-fe
        ports:
        - containerPort: 5000
        env:
        - name: FACTS_SERVER
          value: service-be
        - name: FACTS_PORT
          value: "5000"
