apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -green

resources:
  - ../base

replicas:
  - name: kust
    count: 3

images:
  - name: hub.zahariev.pro/k8s-environ:latest
    newTag: green

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: kust
      spec:
        ports:
          - port: 80
            nodePort: 31101
            protocol: TCP
    target:
      kind: Service
      name: kust
