apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -blue

resources:
  - ../base

images:
  - name: hub.zahariev.pro/k8s-environ:latest
    newTag: blue

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: kust
      spec:
        ports:
          - port: 80
            nodePort: 32101
            protocol: TCP
    target:
      kind: Service
      name: kust
