# Default values for nginx-chart

# Number of replicas for the NGINX deployment
replicaCount: 3

# NGINX image configuration
image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: NodePort
  port: 80
  nodePort: 31000

# Custom index.html content
indexHtml:
  text: "Welcome to my NGINX server managed by Helm!"
  imageUrl: "https://kubernetes.io/images/kubernetes-horizontal-color.png"
